#!/usr/bin/env python3
"""translate_md — EN-US -> PT-BR for pubs/proposal, markdown-aware, hash-cached.

    python3 scripts/translate_md.py            # translate files whose EN hash changed
    python3 scripts/translate_md.py --force    # everything
    python3 scripts/translate_md.py --dry-run  # list what would run, no API calls

Backend: any OpenAI-compatible endpoint. Default is GitHub Models with GITHUB_TOKEN;
TRANSLATE_BASE_URL / TRANSLATE_MODEL / TRANSLATE_API_KEY override (e.g. a local Ollama:
TRANSLATE_BASE_URL=http://127.0.0.1:11434/v1 TRANSLATE_MODEL=llama3.2 TRANSLATE_API_KEY=ollama).
Protected before the call and restored after: fenced code, inline code, math, link/image
targets, citation keys, HTML comments, section headings (mapped by a fixed glossary, not by
the model) and pandoc's `Table:` caption keyword.
Adapted from forecast-energy-demand/scripts/translate_latex.py.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "pubs" / "proposal" / "en"
OUT_DIR = ROOT / "pubs" / "proposal" / "pt"
CACHE = ROOT / "pubs" / "proposal" / ".translation-cache.json"
HEADER = "<!-- generated by scripts/translate_md.py from ../en/{name} — edit the English, not this file -->\n"
HEADINGS = {  # fixed glossary: the DEL section names
    "TITLE": "TÍTULO", "EMPHASIS": "ÊNFASE", "THEME": "TEMA", "SCOPE": "DELIMITAÇÃO",
    "JUSTIFICATION": "JUSTIFICATIVA", "OBJECTIVE": "OBJETIVO", "METHODOLOGY": "METODOLOGIA",
    "SCHEDULE": "CRONOGRAMA", "References": "Referências Bibliográficas",
}

PATTERNS = [
    re.compile(r"```.*?```", re.S),            # fenced code
    re.compile(r"<!--.*?-->", re.S),           # html comments
    re.compile(r"\$\$.*?\$\$", re.S),          # display math
    re.compile(r"(?<!\$)\$[^$\n]+?\$(?!\$)"),  # inline math
    re.compile(r"`[^`\n]+`"),                  # inline code
    re.compile(r"\]\([^)]*\)"),                # link / image targets
    re.compile(r"\[-?@[^\]]+\]|(?<![\w@])@[A-Za-z0-9_:-]+"),  # citations
    re.compile(r"^# .+$", re.M),               # section headings: mapped by the glossary, not the model
    re.compile(r"^Table:", re.M),              # pandoc caption keyword
]
PH = "⟦{}⟧"
PH_RE = re.compile(r"⟦(\d+)⟧")

SYSTEM = """You are an academic translator (engineering / computer science). Translate the markdown
from American English to Brazilian Portuguese. Rules: translate prose, table cells and list
items only; keep every ⟦N⟧ placeholder exactly as is and in place; keep markdown structure
(lists, tables, emphasis, blank lines) unchanged; do not add or remove paragraphs; keep proper
nouns, acronyms and product names (WAVEWATCH III, WW3, WW4, ReNOMO, LabECO, UFSC, NOAA,
Kokkos, H100) as they are; output only the translated markdown, no preamble."""


class PlaceholderError(RuntimeError):
    pass


def protect(text: str) -> tuple[str, list[str]]:
    table: list[str] = []

    def stash(m: re.Match) -> str:
        table.append(m.group(0))
        return PH.format(len(table) - 1)

    for pat in PATTERNS:
        text = pat.sub(stash, text)
    return text, table


def localize_headings(table: list[str]) -> list[str]:
    out = []
    for item in table:
        m = re.match(r"^# (.+?)( \{[^}]*\})?$", item)
        if m and m.group(1) in HEADINGS:
            item = f"# {HEADINGS[m.group(1)]}{m.group(2) or ''}"
        elif m:
            raise PlaceholderError(f"heading not in the DEL glossary: {item}")
        out.append(item)
    return out


def restore(masked: str, table: list[str]) -> str:
    found = {int(n) for n in PH_RE.findall(masked)}
    missing = sorted(set(range(len(table))) - found)
    if missing:
        raise PlaceholderError(f"placeholders lost by the model: {missing}")
    # Placeholders can nest (a citation inside a link text), so restore until none remain.
    prev = None
    while prev != masked:
        prev = masked
        masked = PH_RE.sub(lambda m: table[int(m.group(1))], masked)
    return masked


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def client():
    from openai import OpenAI
    base = os.environ.get("TRANSLATE_BASE_URL", "https://models.github.ai/inference")
    key = os.environ.get("TRANSLATE_API_KEY") or os.environ.get("GITHUB_TOKEN")
    if not key:
        sys.exit("translate_md: set GITHUB_TOKEN (GitHub Models) or TRANSLATE_API_KEY/TRANSLATE_BASE_URL")
    return OpenAI(base_url=base, api_key=key), os.environ.get("TRANSLATE_MODEL", "openai/gpt-4o-mini")


def translate_text(cl, model: str, masked: str) -> str:
    r = cl.chat.completions.create(
        model=model, temperature=0.2,
        messages=[{"role": "system", "content": SYSTEM}, {"role": "user", "content": masked}],
    )
    out = r.choices[0].message.content.strip()
    out = re.sub(r"^```(?:markdown)?\n|\n```$", "", out)  # some models wrap the answer in a fence
    return out + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    todo = []
    for src_f in sorted(SRC_DIR.glob("[0-9][0-9]-*.md")):
        h = sha(src_f.read_text(encoding="utf-8"))
        out_f = OUT_DIR / src_f.name
        if a.force or cache.get(src_f.name) != h or not out_f.exists():
            todo.append((src_f, h))
    if not todo:
        print("translate_md: everything up to date")
        return 0
    for src_f, _ in todo:
        print(f"translate_md: {'would translate' if a.dry_run else 'translating'} {src_f.name}")
    if a.dry_run:
        return 0
    cl, model = client()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rc = 0
    for src_f, h in todo:
        src = src_f.read_text(encoding="utf-8")
        masked, table = protect(src)
        try:
            out = restore(translate_text(cl, model, masked), localize_headings(table))
        except PlaceholderError as e:
            print(f"translate_md: {src_f.name}: {e} — PT copy left untouched", file=sys.stderr)
            rc = 1
            continue
        (OUT_DIR / src_f.name).write_text(HEADER.format(name=src_f.name) + out, encoding="utf-8")
        cache[src_f.name] = h
        CACHE.write_text(json.dumps(cache, indent=2, sort_keys=True) + "\n")
    return rc


if __name__ == "__main__":
    sys.exit(main())
